// fullstack/nextjs/src/app/(main)/components/HeaderProfile/index.tsx
"use client";

import { DownOutlined, LogoutOutlined } from "@ant-design/icons";
import { Dropdown, Space } from "antd";
import useAuth from "@/client/hooks/useAuth";
import { signOut } from "@/server/action/auth.action";

export default function HeaderProfile() {
  const { user } = useAuth();

  return (
    <div className="mb-6 flex justify-end px-8">
      <Dropdown
        trigger={["click"]}
        placement="bottomRight"
        menu={{
          items: [
            {
              key: "1",
              label: "Sign Out",
              icon: <LogoutOutlined className="!text-base" />,
              onClick: () => signOut(),
            },
          ],
        }}
      >
        <Space size={16} className="cursor-pointer">
          <Space direction="vertical" size={0}>
            <p>{user.name}</p>
            <p className="text-xs">{user.bio}</p>
          </Space>
          <DownOutlined />
        </Space>
      </Dropdown>
    </div>
  );
}

// frontend/vue/src/components/HeaderProfile.vue
<script setup lang="ts">
import { DownOutlined, LogoutOutlined } from '@ant-design/icons-vue'
import { Dropdown, Menu } from 'ant-design-vue'
import { useAuthStore } from '@/stores/auth'

const authStore = useAuthStore()
</script>

<template>
  <div class="mb-6 flex justify-end px-8">
    <Dropdown placement="bottomRight">
      <template #overlay>
        <Menu>
          <Menu.Item key="1" @click="authStore.logout">
            <LogoutOutlined class="mr-2 text-base" />
            Sign Out
          </Menu.Item>
        </Menu>
      </template>

      <div class="flex cursor-pointer items-center gap-4">
        <div class="flex flex-col">
          <p>{{ authStore.user?.name }}</p>
          <p class="text-xs text-gray-500">{{ authStore.user?.bio }}</p>
        </div>
        <DownOutlined />
      </div>
    </Dropdown>
  </div>
</template>
