// frontend/vue/src/components/ContactForm.vue
<script setup lang="ts">
import { ADD_CONTACT_MUTATION, UPDATE_CONTACT_MUTATION } from '@/mutations/contact'
import { MinusCircleOutlined, PlusOutlined } from '@ant-design/icons-vue'
import { useMutation } from '@vue/apollo-composable'
import { Button, Col, Form, Input, Row, notification } from 'ant-design-vue'
import { reactive } from 'vue'
import { useRouter } from 'vue-router'

const props = defineProps({
  id: String,
  initialValue: Object,
})

const router = useRouter()

interface FormState {
  fullName: string
  nickName?: string
  postalCode?: string
  phoneNumber: string
  email?: string
  addresses: any[]
}

const formState = reactive<FormState>(
  props.initialValue
    ? JSON.parse(JSON.stringify(props.initialValue))
    : {
        fullName: '',
        phoneNumber: '',
        addresses: [],
      },
)

const { mutate: saveContact, loading } = useMutation(
  props.id ? UPDATE_CONTACT_MUTATION : ADD_CONTACT_MUTATION,
)

const normalizePostalCode = (address: any) => {
  address.postalCode = address.postalCode.replace(/\D/g, '')
}

const addAddress = () => {
  if (formState.addresses) {
    formState.addresses.push({
      street: '',
      city: '',
      district: '',
      subDistrict: '',
      postalCode: '',
    })
  } else {
    formState.addresses = [
      {
        street: '',
        city: '',
        district: '',
        subDistrict: '',
        postalCode: '',
      },
    ]
  }
}

const removeAddress = (index: number) => {
  formState?.addresses?.splice(index, 1)
}

const onFinish = async (values: any) => {
  try {
    const result = await saveContact({
      ...values,
      id: props.id,
    })
    if (result?.errors) {
      throw result
    }
    notification.success({
      message: 'Success',
      description: 'Contact saved successfully',
    })
    router.replace('/contacts')
  } catch (error: any) {
    if (error.errors) {
      notification.error({
        message: 'Error',
        description: error.errors.errorMsg,
      })
    } else {
      notification.error({
        message: 'Error',
        description: error.message || 'Save Contact failed, please try again.',
      })
    }
  }
}
</script>

<template>
  <Form :model="formState" layout="vertical" @finish="onFinish">
    <Form.Item name="fullName" :rules="[{ required: true }]">
      <Input v-model:value="formState.fullName" placeholder="Full Name" />
    </Form.Item>

    <Form.Item name="nickName">
      <Input v-model:value="formState.nickName" placeholder="Nick Name" />
    </Form.Item>

    <Form.Item name="phoneNumber" :rules="[{ required: true }]">
      <Input v-model:value="formState.phoneNumber" placeholder="Phone Number" />
    </Form.Item>

    <Form.Item name="email">
      <Input v-model:value="formState.email" placeholder="Email" />
    </Form.Item>

    <Form.Item v-for="(address, index) in formState.addresses" :key="index">
      <Row :gutter="[16, 16]">
        <Col :span="1">
          <span>{{ index + 1 }}.</span>
        </Col>
        <Col :span="20">
          <Form.Item :name="['addresses', index, 'street']" :rules="[{ required: true }]">
            <Input v-model:value="address.street" placeholder="Street" />
          </Form.Item>
        </Col>
        <Col :span="2">
          <MinusCircleOutlined @click="removeAddress(index)" />
        </Col>
      </Row>
      <Row :gutter="[16, 16]">
        <Col :span="1"> </Col>
        <Col :span="10">
          <Form.Item :name="['addresses', index, 'city']">
            <Input v-model:value="address.city" placeholder="City" />
          </Form.Item>
        </Col>
        <Col :span="10">
          <Form.Item :name="['addresses', index, 'district']">
            <Input v-model:value="address.district" placeholder="District" />
          </Form.Item>
        </Col>
      </Row>
      <Row :gutter="[16, 16]">
        <Col :span="1"> </Col>
        <Col :span="10">
          <Form.Item :name="['addresses', index, 'subDistrict']">
            <Input v-model:value="address.subDistrict" placeholder="Sub District" />
          </Form.Item>
        </Col>
        <Col :span="10">
          <Form.Item :name="['addresses', index, 'postalCode']">
            <Input
              v-model:value="address.postalCode"
              placeholder="Postal Code"
              @input="normalizePostalCode(address)"
            />
          </Form.Item>
        </Col>
      </Row>
    </Form.Item>

    <Form.Item>
      <Button type="dashed" block @click="addAddress"> <PlusOutlined /> Add Address </Button>
    </Form.Item>

    <Form.Item>
      <Button type="primary" html-type="submit" block :loading="loading">Save</Button>
    </Form.Item>
  </Form>
</template>

<style scoped></style>

// fullstack/nextjs/src/app/(main)/contacts/components/ContactForm/index.tsx
"use client";

import { Button, Col, Form, Input, Row, Select, Typography } from "antd";
import { Fragment, useEffect } from "react";
import { MinusCircleOutlined, PlusOutlined } from "@ant-design/icons";
import { useRouter } from "next/navigation";
import { ContactType } from "../../data";
import useData from "@/client/hooks/useData";
import useNotification from "@/client/hooks/useNotification";

interface ContactFormProps {
  id?: number;
  initialValues?: ContactType;
  onSubmit: (
    values: any,
    id?: number,
  ) => Promise<{ errorMsg: string } | undefined>;
}

export default function ContactForm({
  id,
  initialValues,
  onSubmit,
}: ContactFormProps) {
  const { showNotification } = useNotification();
  const router = useRouter();

  const { dialCodes, getDialCodes } = useData();

  async function handleSubmit(values: any) {
    values.phoneNumber = values.dialCode + "-" + values.phoneNumber;
    const result = await onSubmit(values, id);
    if (result?.errorMsg) {
      showNotification.error({
        message: "Error",
        description: result.errorMsg,
      });
    } else {
      showNotification.success({
        message: "Success",
        description: "Contact saved successfully",
      });
      router.push("/contacts");
    }
  }

  useEffect(() => {
    getDialCodes();
  }, []);
  return (
    <Form
      onFinish={handleSubmit}
      layout="vertical"
      initialValues={
        initialValues
          ? {
              ...initialValues,
              dialCode: initialValues?.phoneNumber.split("-")[0],
              phoneNumber: initialValues?.phoneNumber.split("-")[1],
            }
          : {
              dialCode: "+62",
            }
      }
    >
      <Form.Item name="fullName" rules={[{ required: true }]}>
        <Input placeholder="Full Name" />
      </Form.Item>
      <Form.Item name="nickName">
        <Input placeholder="Nick Name" />
      </Form.Item>
      <Form.Item
        name="phoneNumber"
        rules={[{ required: true }]}
        normalize={(value: string) => {
          if (value.startsWith("0")) {
            return value.replace("0", "");
          }
          return value.replace(/\D/g, "");
        }}
      >
        <Input
          placeholder="Phone Number"
          addonBefore={
            <Form.Item name="dialCode" noStyle rules={[{ required: true }]}>
              <Select
                style={{ width: 85 }}
                notFoundContent={null}
                showSearch
                filterOption={(input, option) =>
                  (option?.label ?? "")
                    .toLowerCase()
                    .includes(input.toLowerCase())
                }
                options={dialCodes.map((dialCode) => ({
                  value: dialCode.dial_code,
                  label: dialCode.dial_code,
                  key: dialCode.code,
                }))}
              />
            </Form.Item>
          }
        />
      </Form.Item>
      <Form.Item name="email" className="!mb-12">
        <Input placeholder="Email" />
      </Form.Item>
      <Form.List name="addresses">
        {(fields, { add, remove }) => (
          <>
            {fields.map(({ key, name, ...restField }, index) => (
              <Fragment key={key}>
                <Row className="mb-2 flex" align="middle" gutter={[16, 16]}>
                  <Col span={1}>
                    <Typography.Text className="mb-7 block text-nowrap">
                      {index + 1 + "."}
                    </Typography.Text>
                  </Col>
                  <Col span={20}>
                    <Form.Item
                      {...restField}
                      className="w-full"
                      name={[name, "street"]}
                      rules={[{ required: true }]}
                    >
                      <Input placeholder="Street" />
                    </Form.Item>
                  </Col>
                </Row>
                <Row className="mb-2 flex" align="middle" gutter={[16, 16]}>
                  <Col offset={1} span={10}>
                    <Form.Item
                      {...restField}
                      className="w-full"
                      name={[name, "city"]}
                    >
                      <Input placeholder="City" />
                    </Form.Item>
                  </Col>
                  <Col span={10}>
                    <Form.Item
                      {...restField}
                      className="w-full"
                      name={[name, "district"]}
                    >
                      <Input placeholder="District" />
                    </Form.Item>
                  </Col>
                </Row>
                <Row className="mb-2 flex" align="middle" gutter={[16, 16]}>
                  <Col offset={1} span={10}>
                    <Form.Item
                      {...restField}
                      className="w-full"
                      name={[name, "subDistrict"]}
                    >
                      <Input placeholder="Sub District" />
                    </Form.Item>
                  </Col>
                  <Col span={10}>
                    <Form.Item
                      {...restField}
                      className="w-full"
                      name={[name, "postalCode"]}
                      normalize={(value: string) => {
                        return value.replace(/\D/g, "");
                      }}
                    >
                      <Input placeholder="Postal Code" />
                    </Form.Item>
                  </Col>
                  <Col span={2}>
                    <MinusCircleOutlined
                      onClick={() => remove(name)}
                      className="mb-7"
                    />
                  </Col>
                </Row>
              </Fragment>
            ))}
            <Form.Item>
              <Button
                type="dashed"
                onClick={() => add()}
                block
                icon={<PlusOutlined />}
              >
                Add Address
              </Button>
            </Form.Item>
          </>
        )}
      </Form.List>
      <Form.Item className="!mt-16 w-full">
        <Button htmlType="submit" type="primary" className="w-full">
          Save
        </Button>
      </Form.Item>
    </Form>
  );
}
