// fullstack/sveltekit/src/routes/(public)/sign-up/+page.svelte
<script lang="ts">
	import FormInput from '$lib/components/FormInput.svelte';

	let { form } = $props();
</script>

<div
	class="flex min-h-screen w-full max-w-96 items-center justify-center font-[family-name:var(--font-geist-sans)]"
>
	<main class="row-start-2 flex w-full flex-col items-center gap-8 sm:items-start">
		<h1 class="w-full text-center text-3xl font-semibold">Sign Up</h1>
		<form class="w-full" method="POST" action="/sign-up">
			<FormInput id="name" name="name" errors={form?.errors} className="w-full">
				<input
					id="name"
					name="name"
					placeholder="Full Name"
					type="text"
					class="w-full rounded-md p-2 text-xs placeholder:text-xs"
				/>
			</FormInput>
			<FormInput id="email" name="email" errors={form?.errors} className="w-full">
				<input
					id="email"
					name="email"
					autocomplete="email webauthn"
					placeholder="Email"
					type="email"
					class="w-full rounded-md p-2 text-xs placeholder:text-xs"
				/>
			</FormInput>
			<FormInput id="phoneNumber" name="phoneNumber" errors={form?.errors} className="w-full">
				<input
					id="phoneNumber"
					name="phoneNumber"
					placeholder="Phone Number"
					type="text"
					class="w-full rounded-md p-2 text-xs placeholder:text-xs"
				/>
			</FormInput>
			<FormInput id="bio" name="bio" errors={form?.errors} className="w-full">
				<input
					id="bio"
					name="bio"
					placeholder="Bio"
					type="text"
					class="w-full rounded-md p-2 text-xs placeholder:text-xs"
				/>
			</FormInput>
			<FormInput id="password" name="password" errors={form?.errors} className="w-full">
				<input
					id="password"
					name="password"
					autocomplete="new-password webauthn"
					placeholder="Password"
					type="password"
					class="w-full rounded-md p-2 text-xs placeholder:text-xs"
				/>
			</FormInput>

			<div class="mt-12 w-full">
				<button
					type="submit"
					class="bg-primary w-full cursor-pointer rounded-md px-3 py-2 text-sm text-white shadow-xs"
					>Sign Up</button
				>
				{#if form?.errorMsg}
					<div
						class="min-h-6 px-1 pt-1 text-center whitespace-pre-line text-red-600"
						aria-invalid="true"
					>
						{form.errorMsg}
					</div>
				{/if}
			</div>
		</form>
		<div class="flex w-full items-center justify-center gap-2">
			<p>Already have an account?</p>
			<a href="/sign-in" class="text-link"> Sign In </a>
		</div>
	</main>
</div>

// fullstack/nextjs/src/app/(auth)/sign-up/page.tsx
"use client";

import { Button, Form, Input, Select } from "antd";
import { useEffect } from "react";
import { useRouter } from "next/navigation";
import { signUp } from "./action";
import useData from "@/client/hooks/useData";
import useNotification from "@/client/hooks/useNotification";

export default function SignUp() {
  const { showMessage } = useNotification();
  const router = useRouter();

  const { dialCodes, getDialCodes } = useData();

  async function onSignUp(values: any) {
    values.phoneNumber = values.dialCode + "-" + values.phoneNumber;
    const result = await signUp(values);
    if (result?.errorMsg) {
      showMessage.error(result.errorMsg, 5);
    } else {
      showMessage.success("Sign up successfully, please sign in", 5);
      router.replace("/sign-in");
    }
  }

  useEffect(() => {
    getDialCodes();
  }, []);

  return (
    <div className="flex min-h-screen w-full max-w-96 items-center justify-center font-[family-name:var(--font-geist-sans)]">
      <main className="row-start-2 flex w-full flex-col items-center gap-8 sm:items-start">
        <h1 className="w-full text-center text-3xl font-semibold">Sign Up</h1>
        <Form
          onFinish={onSignUp}
          className="w-full"
          layout="vertical"
          initialValues={{
            dialCode: "+62",
          }}
        >
          <Form.Item name="name" rules={[{ required: true }]}>
            <Input placeholder="Full Name" />
          </Form.Item>
          <Form.Item name="email" rules={[{ required: true }]}>
            <Input placeholder="Email" />
          </Form.Item>
          <Form.Item
            name="phoneNumber"
            rules={[{ required: true }]}
            normalize={(value: string) => {
              if (value.startsWith("0")) {
                return value.replace("0", "");
              }
              return value.replace(/\D/g, "");
            }}
          >
            <Input
              placeholder="Phone Number"
              addonBefore={
                <Form.Item name="dialCode" noStyle rules={[{ required: true }]}>
                  <Select
                    style={{ width: 85 }}
                    notFoundContent={null}
                    showSearch
                    filterOption={(input, option) =>
                      (option?.label ?? "")
                        .toLowerCase()
                        .includes(input.toLowerCase())
                    }
                    options={dialCodes.map((dialCode) => ({
                      value: dialCode.dial_code,
                      label: dialCode.dial_code,
                      key: dialCode.code,
                    }))}
                  />
                </Form.Item>
              }
            />
          </Form.Item>
          <Form.Item name="bio">
            <Input placeholder="Bio" />
          </Form.Item>
          <Form.Item name="password" rules={[{ required: true }]}>
            <Input.Password
              placeholder="Password"
              autoComplete="new-password"
            />
          </Form.Item>
          <Form.Item className="!mb-0 !mt-12 w-full">
            <Button htmlType="submit" type="primary" className="w-full">
              Sign Up
            </Button>
          </Form.Item>
        </Form>
        <div className="flex w-full items-center justify-center">
          <p>Already have an account?</p>
          <Button href="/sign-in" type="link">
            Sign In
          </Button>
        </div>
      </main>
    </div>
  );
}
